services:
  interface:
    build: ./interface
    ports:
      - 3000:3000
    volumes:
      - ./app:/app

  server:
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/app

