services:
  interface:
    build: ./interface
    container_name: interface
    restart: always
    depends_on:
      - server
    ports:
      - 3000:3000
    volumes:
      - app:/app

  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./server:/app

volumes:
  app:
